// <auto-generated />
namespace Practical_12_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dobfield2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dobfield2));
        
        string IMigrationMetadata.Id
        {
            get { return "202202140941391_dobfield2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
